# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VAtbsPNBDwnUfsupyOukHTgSMXfasWod
"""

import pandas as pd

df=pd.read_csv("/content/country_vaccination_stats.csv")

df

df['daily_vaccinations'].fillna(df.groupby('country')['daily_vaccinations'].transform('min'), inplace=True)

df['daily_vaccinations'].fillna(0, inplace=True)

df.isna().sum()