# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erhfFXTZc4pVuZe_tiLhXs-nSk0yIJT0
"""

import pandas as pd

df = pd.read_csv("/content/country_vaccination_stats.csv")

total_vaccinations_1_6_2021 = df[df['date'] == '1/6/2021']['daily_vaccinations'].sum()

print("Total number of vaccines administered on 1/6/2021:", total_vaccinations_1_6_2021)